# Generated by Django 4.2.29 on 2026-04-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
