# Generated by Django 4.2.29 on 2026-04-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='seats_available',
            new_name='total_seats',
        ),
    ]
